#!/usr/bin/python

from p_admin.models import  EsthenosSettings,EsthenosUser
from p_organisation.models import EsthenosOrgApplicationHighMark,EsthenosOrgApplicationHighMarkRequest,EsthenosOrgApplication

user = EsthenosUser.create_user("admin","admin@esthenos.com","Admin312",True)
user.add_role("ADMIN")
user.first_name = "Admin"
user.last_name = ""
user.username = "Admin"
user.active = True
user.save()

if len(EsthenosSettings.objects.all()) ==1:
    EsthenosSettings.objects.all()[0].delete()

settings = EsthenosSettings()
EsthenosSettings=EsthenosSettings()
EsthenosSettings=EsthenosSettings()

print settings
settings.save()
#Added by Deepak
if len(EsthenosOrgApplicationHighMarkRequest.objects.all()) ==1:
    EsthenosOrgApplicationHighMarkRequest.objects.all()[0].delete()

Highmarkrequest = EsthenosOrgApplicationHighMarkRequest()
Highmarkrequest.applicant_id1("GJ/19/137/370571")
Highmarkrequest.acct_open_date("")
Highmarkrequest.applicant_address1("44 MACHHLEL TA MATAR DIST KHEDA")
Highmarkrequest.applicant_address1_city("MACHEL")
Highmarkrequest.applicant_address1_pincode("387530")
Highmarkrequest.applicant_address1_state("GJ")
Highmarkrequest.applicant_address2("")
Highmarkrequest.applicant_address2_city("")
Highmarkrequest.applicant_address2_pincode("")
Highmarkrequest.applicant_address2_state("")
Highmarkrequest.applicant_address_type1("D12")
Highmarkrequest.applicant_address_type2("")
Highmarkrequest.applicant_age("40")
Highmarkrequest.applicant_age_as_on_date("05/03/2015 16:32:00")
Highmarkrequest.applicant_birth_date("05/03/2015 16:32:00")
Highmarkrequest.applicant_id__account_no("")
Highmarkrequest.applicant_id_type1("ID02")
Highmarkrequest.applicant_id_type2("ID05")
Highmarkrequest.applicant_name1("PARMAR BHEEKHEEBEN")
Highmarkrequest.applicant_name2("")
Highmarkrequest.applicant_name3("")
Highmarkrequest.applicant_name4("")
Highmarkrequest.applicant_name5("")
Highmarkrequest.applicant_telephone_number1("9574040983")
Highmarkrequest.applicant_telephone_number2("")
Highmarkrequest.applied_for_amount__current_balance("20000")
Highmarkrequest.branch_id("KHEDA")
Highmarkrequest.credit_inquiry_purpose_type("ACCT-ORIG")
Highmarkrequest.credit_inquiry_purpose_type_description("")
Highmarkrequest.credit_inquiry_stage("PRE-SCREEN")
Highmarkrequest.credit_report_transaction_date_time("0000-00-00 00:00:00")
Highmarkrequest.credit_report_transaction_id("")
Highmarkrequest.credit_request_type("JOIN")
Highmarkrequest.kendra_id("MACHHIYEL TALAVFALIYU")
Highmarkrequest.key_person_name("")
Highmarkrequest.key_person_relation("")
Highmarkrequest.member_father_name("UPGSINH")
Highmarkrequest.member_id("GJ8509005")
Highmarkrequest.member_mother_name("")
Highmarkrequest.member_relationship_name1("PARMAR DINESHBHAI")
Highmarkrequest.member_relationship_name2("PARMAR DINESHBHAI")
Highmarkrequest.member_relationship_name3("")
Highmarkrequest.member_relationship_name4("")
Highmarkrequest.member_relationship_type1("K02")
Highmarkrequest.member_relationship_type2("K01")
Highmarkrequest.member_relationship_type3("")
Highmarkrequest.member_relationship_type4("")
Highmarkrequest.member_mother_name("")
Highmarkrequest.member_spouse_name("DINESHBHAI")
Highmarkrequest.nominee_name("")
Highmarkrequest.segment_identifier("CRDRQINQR")
Highmarkrequest.sent_status("")
print Highmarkrequest
Highmarkrequest.save()
#Added By Deepak
if len(EsthenosOrgApplicationHighMark.objects.all()) ==1:
   EsthenosOrgApplicationHighMark.objects.all()[0].delete()

Highmarkresponse = EsthenosOrgApplicationHighMark()
Highmarkresponse.active_account("0")
Highmarkresponse.address("#81 MARIMUDDANAHALLI HUNSURE TO MYSOURE KARIMUDDANAHALLI 571189 KA")
Highmarkresponse.age_as_on_dt("")
Highmarkresponse.application_id("")
Highmarkresponse.branch("MYSORE3")
Highmarkresponse.closed_account("0")
Highmarkresponse.default_account("0")
Highmarkresponse.dob_age("1-1-1959")
Highmarkresponse.driving_lic("")
Highmarkresponse.error_descripton("")
Highmarkresponse.father_name("")
Highmarkresponse.kendra("KARIMUDDANAHALLI")
Highmarkresponse.mbr_rel_name1("GOVINDEGOWDA")
Highmarkresponse.mbr_rel_name2("GARIGOWDA")
Highmarkresponse.member_id("KA1031411")
Highmarkresponse.member_name("LAXMAMMA")
Highmarkresponse.oth_active("0")
Highmarkresponse.oth_all("0")
Highmarkresponse.other_disb_atm("201442")
Highmarkresponse.other_id_type1("")
Highmarkresponse.other_id_val1("")
Highmarkresponse.own("false")
Highmarkresponse.own_disb_atm("0")
Highmarkresponse.phone("'8693947846")
Highmarkresponse.pri("5")
Highmarkresponse.ration_card("")
Highmarkresponse.rel_type1("(Father)")
Highmarkresponse.rel_type2("(Husband)")
Highmarkresponse.remark("Borrower has more than 2 Active loans")
Highmarkresponse.report_id("FFSL140909CR72163129")
Highmarkresponse.sec("1")
Highmarkresponse.spouse_name("SRINIVAS")
Highmarkresponse.status("SUCCESS")
Highmarkresponse.value("Over Exposure")
Highmarkresponse.voter_id("ACS35085")
print Highmarkresponse
Highmarkresponse.save()

#Added By Deepak
if len(EsthenosOrgApplication.objects.all()) ==1:
   EsthenosOrgApplication.objects.all()[0].delete()

EsthenosOrgApplication = EsthenosOrgApplication()
EsthenosOrgApplication.aadhaar_card("565061987998")
EsthenosOrgApplication.address("Hal")
EsthenosOrgApplication.age("40")
EsthenosOrgApplication.applicant_name("Loan")
EsthenosOrgApplication.application_id("45D")
EsthenosOrgApplication.attendence_percentage("40")
EsthenosOrgApplication.business_expense("456789")
EsthenosOrgApplication.center("Hal")
EsthenosOrgApplication.current_status("")
EsthenosOrgApplication.date_created("12/1/2014")
EsthenosOrgApplication.date_updated("12/1/2014")
EsthenosOrgApplication.defaults_with_no_mfis("")
EsthenosOrgApplication.dob("12/1/2045")
EsthenosOrgApplication.educational_expense("20000")
EsthenosOrgApplication.eligible_loan_cycle("1")
EsthenosOrgApplication.entertainment_expense("200")
EsthenosOrgApplication.existing_loan_cycle("2")
EsthenosOrgApplication.food_expense("20")
EsthenosOrgApplication.gender("F")
EsthenosOrgApplication.group("")
EsthenosOrgApplication.loan_eligibility_based_on_company_policy("")
EsthenosOrgApplication.loan_eligibility_based_on_net_income("")
EsthenosOrgApplication.medical_expense("100")
EsthenosOrgApplication.net_income("1000")
EsthenosOrgApplication.organisation("sarmik")
EsthenosOrgApplication.other_expense("100")
EsthenosOrgApplication.other_income("45")
EsthenosOrgApplication.other_outstanding_chit("7")
EsthenosOrgApplication.other_outstanding_emi("4")
EsthenosOrgApplication.other_outstanding_insurance("7")
EsthenosOrgApplication.outstanding_1("1")
EsthenosOrgApplication.outstanding_2("1")
EsthenosOrgApplication.outstanding_3("4")
EsthenosOrgApplication.outstanding_4("5")
EsthenosOrgApplication.pan_card("BTRPP2391C")
EsthenosOrgApplication.primary_income("12")
EsthenosOrgApplication.secondary_income("1")
EsthenosOrgApplication.status("")
EsthenosOrgApplication.tag("")
EsthenosOrgApplication.tertiary_income("4")
EsthenosOrgApplication.timeline("1")
EsthenosOrgApplication.total_existing_outstanding_from("1")
EsthenosOrgApplication.total_existing_outstanding_from_mfi("1")
EsthenosOrgApplication.total_expenditure("45")
EsthenosOrgApplication.total_income("14")
EsthenosOrgApplication.total_liability("12")
EsthenosOrgApplication.travel_expense("45")
EsthenosOrgApplication.upload_type("simple")
EsthenosOrgApplication.vid_card("bvcbb")
EsthenosOrgApplication.total_running_loans("5")
EsthenosOrgApplication.total_other_outstanding("4")
EsthenosOrgApplication.total_outstanding("56")
print EsthenosOrgApplication
EsthenosOrgApplication.save()